const CartActionTypes = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREASE_QUANTITY_OF_ITEM: "INCREASE_QUANTITY_OF_ITEM",
  DECREASE_QUANTITY_OF_ITEM: "DECREASE_QUANTITY_OF_ITEM"
};

export default CartActionTypes;
